language: node_js
node_js:
- '8'
install: true
deploy:
  provider: heroku
  api_key:
    secure: W1YSaI5ab7WNU7i23UVlxMWJYt9A+JX2A9pzkwLzpgP9EQqjHe0Vp7KVKgokz25fcylqKuwhCuAHSReS2TzFlL1tjGdOO5sg00pg5F53U2gu7eEclBKT1lb5JWRjI+VgihUXSyoQJBX7g5nCVM8KdfnE8cmKjVkA3YOB5avcJvMRhMKV2nYMzBA0XuvWGddB6Mf+1WS3rBlh1L0k9urrsZLxbm3dn2sYx4udk31Gp5UvT1+AdyKpMY4zdLVZfV8Xf4AJ2LajRO+qt+84ediensLQB1qQwCqKfWWyj8/dzfkEsPwKZ9uXuew1sdDGu8tlXZ/IahBLJna98vE1yrueTtpPX5nOFXLY188x0DSGi0bgxnXAk6MR9qspr/2gudvAZWq5c69jt14HteAx94txWDbgsmRAZYk4KO4y9ObVZutWF+WvB9cszOu4HU9VDzLSQbP3xHwYEi3nZNOGX9Oxh5G/ReaH5BGaJBISSYPWQ4Cq1PFsz1qmPzCtY4Kc+u4baIHqmLwawvelrqjBtLyOT9jpXGQswcvbQQBuX8Rn7DnorJMpA/wfj+PCH1NG7RAaOpc9NFVVSwyo+4CLDFG2akcmMPGJXIgqkjLFzTcurE8bT7bL+IHX8dbQv3zbU5wskn2GU59Stm9JLRYFxXmdj8yql49H/sb9MZxDBZGxhrI=
  skip_cleanup: true
  strategy: api
  app: kengurukleo-survey-maker
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_60e2a7f15acb_key -iv $encrypted_60e2a7f15acb_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script:
- cd client
- npm install
- npm run build
- cd ..